### ISSUE TITLE
Resource-Manager should be able to convert DDT to TGA

### ISSUE THREAD

**Issue by mandosrex** [KevinW1998/Resource-Manager#8]
Resource-Manager should be able to convert DDT to TGA, like the old legacy converter, in order to keep the color map and alpha channels separate, unlike the current PNG conversion that fuses them and creates a transparent PNG.
This is important for multiple reasons but also because alpha channels often designate player color as well, not just transparency. So when it is converted to PNG, areas that should display player color become transparent instead.

**Comment by VladTheJunior** [comment]
First of all, I released version 0.4.2 yesterday with ability to convert DDT to TGA. Secondly, if you are talking about unit portraits, they are packed as png in BAR, so app doesn't convert them

**Comment by mandosrex** [comment]
I didn't know you released a new version, my bad. And no, I am talking exclusive about DDT. I will get the new version.
